"""replay columns

Revision ID: 0002_replay
Revises: 0001_initial
Create Date: 2026-08-25 13:50:27.055834
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_replay"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("batch_runs", sa.Column("alert_budget", sa.Double(), nullable=True))
    op.create_unique_constraint(op.f("uq_batch_runs_timestep"), "batch_runs", ["timestep"])
    op.add_column("case_reports", sa.Column("queue_rank", sa.Integer(), nullable=True))
    op.add_column("case_reports", sa.Column("graph_score", sa.Double(), nullable=True))
    op.add_column("transaction_embeddings", sa.Column("graph_score", sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction_embeddings", "graph_score")
    op.drop_column("case_reports", "graph_score")
    op.drop_column("case_reports", "queue_rank")
    op.drop_constraint(op.f("uq_batch_runs_timestep"), "batch_runs", type_="unique")
    op.drop_column("batch_runs", "alert_budget")
    # ### end Alembic commands ###
