"""investigation columns

Revision ID: 0003_investigation
Revises: 0002_replay
Create Date: 2026-08-25 21:33:16.403752
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0003_investigation"
down_revision: str | None = "0002_replay"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_reports", sa.Column("typology_assessment", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "case_reports", sa.Column("recommended_action", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "case_reports",
        sa.Column("investigation_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "typology_references", sa.Column("embedding_model", sa.String(length=120), nullable=True)
    )
    op.add_column("typology_references", sa.Column("document", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("typology_references", "document")
    op.drop_column("typology_references", "embedding_model")
    op.drop_column("case_reports", "investigation_meta")
    op.drop_column("case_reports", "recommended_action")
    op.drop_column("case_reports", "typology_assessment")
    # ### end Alembic commands ###
