"""namespace corpus by embedding model

Revision ID: 0004_corpus_ns
Revises: 0003_investigation
Create Date: 2026-08-26 15:41:37.563476
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0004_corpus_ns"
down_revision: str | None = "0003_investigation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_typology_references_typology_id_chunk_index"),
        "typology_references",
        type_="unique",
    )
    op.create_index(
        "ix_typology_references_embedding_model",
        "typology_references",
        ["embedding_model"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_typology_references_typology_id_chunk_index_embedding_model"),
        "typology_references",
        ["typology_id", "chunk_index", "embedding_model"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_typology_references_typology_id_chunk_index_embedding_model"),
        "typology_references",
        type_="unique",
    )
    op.drop_index("ix_typology_references_embedding_model", table_name="typology_references")
    op.create_unique_constraint(
        op.f("uq_typology_references_typology_id_chunk_index"),
        "typology_references",
        ["typology_id", "chunk_index"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
