"""Drop the primary/secondary queue tier.

Queue membership is XGBoost's ranking and the alert budget, and nothing else.
The tier derived a "primary" or "secondary" label from evidence confidence,
which conflated two independent signals: a case reached the queue because the
scorer ranked it highly, not because the evidence later turned out to be
strong. Confidence remains, as evidence strength; it just no longer pretends
to be a queue decision.

drop queue tier

Revision ID: 0005_drop_tier
Revises: 0004_corpus_ns
Create Date: 2026-08-26 18:23:41.621783
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005_drop_tier"
down_revision: str | None = "0004_corpus_ns"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_reports_queue_tier"), table_name="case_reports")
    op.drop_constraint(op.f("ck_case_reports_queue_tier_valid"), "case_reports", type_="check")
    op.drop_column("case_reports", "queue_tier")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_reports",
        sa.Column("queue_tier", sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    )
    op.create_check_constraint(
        op.f("ck_case_reports_queue_tier_valid"),
        "case_reports",
        "queue_tier::text = ANY (ARRAY['primary'::character varying, 'secondary'::character varying]::text[])",
    )
    op.create_index(
        op.f("ix_case_reports_queue_tier"), "case_reports", ["queue_tier"], unique=False
    )
    # ### end Alembic commands ###
